# Generated by Django 2.1.7 on 2019-06-02 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_study_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 2, 18, 35, 3, 150496, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_study_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='user',
            name='study_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_study_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
