# Generated by Django 2.1.2 on 2019-01-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.CharField(default='THIS_IS_NOT_RECORDED', max_length=128),
        ),
    ]
