# Generated by Django 2.1.2 on 2019-01-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercharacter',
            options={'ordering': ['time_added']},
        ),
        migrations.AddField(
            model_name='usercharacter',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01 00:00'),
            preserve_default=False,
        ),
    ]
