# Generated by Django 2.1.2 on 2019-01-13 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20190112_1749'),
        ('accounts', '0002_auto_20190112_2138'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercharacter',
            unique_together={('user', 'character')},
        ),
    ]
