# Generated by Django 2.1.7 on 2019-02-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190210_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercharacter',
            options={'ordering': ['interval', 'time_added', 'character__pk']},
        ),
        migrations.AddField(
            model_name='usercharacter',
            name='EF',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='usercharacter',
            name='interval',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.AddField(
            model_name='usercharacter',
            name='time_last_learned',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usercharacter',
            name='times_learned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercharacter',
            name='time_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
