# Generated by Django 2.2.1 on 2019-06-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_study_vocab_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cn_level',
            field=models.CharField(default='Beginner', max_length=15),
        ),
    ]
