# Generated by Django 2.1.5 on 2019-02-05 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import learning.models
import learning.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('jiezi_id', models.IntegerField(help_text='enter integer only', primary_key=True, serialize=False)),
                ('chinese', models.CharField(max_length=1)),
                ('pinyin', models.CharField(max_length=10)),
                ('definition_1', models.CharField(max_length=50)),
                ('definition_2', models.CharField(blank=True, max_length=50, null=True)),
                ('explanation_2', models.CharField(blank=True, max_length=200, null=True)),
                ('definition_3', models.CharField(blank=True, max_length=50, null=True)),
                ('explanation_3', models.CharField(blank=True, max_length=200, null=True)),
                ('pinyin_audio', models.FileField(default='error.mp3', help_text='it is ok for now to leave blank', storage=learning.storage.OverwriteFileSystemStorage, upload_to=learning.models.PathAndRename('pinyin_audio/C'))),
                ('color_coded_image', models.ImageField(default='default.jpg', storage=learning.storage.OverwriteFileSystemStorage, upload_to=learning.models.PathAndRename('color_coded_characters/C'))),
                ('stroke_order_image', models.ImageField(default='default.jpg', storage=learning.storage.OverwriteFileSystemStorage, upload_to=learning.models.PathAndRename('animated_stroke_order/C'))),
                ('mnemonic_explanation', models.TextField(max_length=200)),
                ('mnemonic_1', models.IntegerField(help_text='enter number only')),
                ('mnemonic_2', models.IntegerField(blank=True, help_text="enter number only, if it doens't exits, leave BLANK instead of putting 0", null=True)),
                ('mnemonic_3', models.IntegerField(blank=True, help_text="enter number only, if it doens't exits, leave BLANK instead of putting 0", null=True)),
                ('example_1_word', models.CharField(max_length=5)),
                ('example_1_pinyin', models.CharField(max_length=25)),
                ('example_1_character', models.CharField(max_length=50)),
                ('example_1_meaning', models.CharField(max_length=50)),
                ('example_2_word', models.CharField(blank=True, max_length=5, null=True)),
                ('example_2_pinyin', models.CharField(blank=True, max_length=25, null=True)),
                ('example_2_character', models.CharField(blank=True, max_length=50, null=True)),
                ('example_2_meaning', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['jiezi_id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('characters', models.ManyToManyField(to='learning.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=100)),
                ('choice2', models.CharField(max_length=100)),
                ('choice3', models.CharField(max_length=100)),
                ('choice4', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('ans_index', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Radical',
            fields=[
                ('jiezi_id', models.IntegerField(help_text='enter integer only', primary_key=True, serialize=False)),
                ('chinese', models.CharField(max_length=1)),
                ('pinyin', models.CharField(help_text="if it doesn't exist put --", max_length=10)),
                ('definition', models.CharField(max_length=50)),
                ('mnemonic_explanation', models.TextField(blank=True, max_length=100, null=True)),
                ('mnemonic_image', models.ImageField(default='default.jpg', storage=learning.storage.OverwriteFileSystemStorage, upload_to=learning.models.PathAndRename('radical_mnemonic/R'))),
                ('is_phonetic', models.BooleanField()),
                ('is_semantic', models.BooleanField()),
            ],
            options={
                'ordering': ['jiezi_id'],
            },
        ),
    ]
