# Generated by Django 2.1.2 on 2019-01-27 14:34

from django.db import migrations, models
import learning.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radical',
            fields=[
                ('jiezi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chinese', models.CharField(max_length=1)),
                ('pinyin', models.CharField(max_length=10)),
                ('definition', models.CharField(max_length=50)),
                ('mnemonic_image', models.ImageField(default='default.jpg', upload_to=learning.models.radical_path)),
                ('is_phonetic', models.BooleanField()),
                ('is_semantic', models.BooleanField()),
            ],
            options={
                'ordering': ['jiezi_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['jiezi_id']},
        ),
    ]
