# Generated by Django 2.1.7 on 2019-04-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='radicals',
        ),
        migrations.AlterField(
            model_name='character',
            name='mnemonic_explanation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='radical',
            name='mnemonic_explanation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
