# Generated by Django 2.1.2 on 2019-01-27 18:44

from django.db import migrations, models
import learning.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='color_coded_image',
            field=models.ImageField(default='default.jpg', upload_to=learning.models.PathAndRename('characters/', 'color_coded_image')),
        ),
        migrations.AlterField(
            model_name='character',
            name='jiezi_id',
            field=models.IntegerField(help_text='enter integer only', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='mnemonic_explanation',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='pinyin_audio',
            field=models.FileField(default='error.mp3', help_text='it is ok for now to leave blank', upload_to=learning.models.PathAndRename('characters/', 'pinyin_audio')),
        ),
        migrations.AlterField(
            model_name='character',
            name='stroke_order_image',
            field=models.ImageField(default='default.jpg', upload_to=learning.models.PathAndRename('characters/', 'stroke_order_image')),
        ),
        migrations.AlterField(
            model_name='radical',
            name='definition',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='radical',
            name='jiezi_id',
            field=models.IntegerField(help_text='enter integer only', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='radical',
            name='mnemonic_image',
            field=models.ImageField(default='default.jpg', upload_to=learning.models.PathAndRename('radicals/', 'mnemonic_image')),
        ),
        migrations.AlterField(
            model_name='radical',
            name='pinyin',
            field=models.CharField(help_text="if it doesn't exist put --", max_length=10),
        ),
    ]
