# Generated by Django 2.1.7 on 2019-04-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20190412_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='part_of_speech_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='part_of_speech_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
