# Generated by Django 2.1.2 on 2019-01-11 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_characterset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterset',
            old_name='character',
            new_name='characters',
        ),
    ]
