# Generated by Django 2.1.2 on 2019-01-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20190127_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='mnemonic_1',
            field=models.IntegerField(help_text='enter number only'),
        ),
    ]
