# Generated by Django 2.1.2 on 2019-01-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20190127_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='radical',
            name='mnemonic_explanation',
            field=models.TextField(default='--', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radical',
            name='definition',
            field=models.CharField(default='--', max_length=50),
        ),
    ]
