# Generated by Django 2.1.2 on 2019-01-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20190127_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radical',
            name='definition',
            field=models.CharField(max_length=50),
        ),
    ]
