# Generated by Django 2.1.5 on 2019-02-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20190204_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='current_characeter_pk',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='current_stage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
