# Generated by Django 2.1.5 on 2019-02-11 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_auto_20190210_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='current_characeter_pk',
            new_name='current_character_pk',
        ),
    ]
