# Generated by Django 2.1.7 on 2019-05-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['origin']},
        ),
    ]
