# Generated by Django 2.1.7 on 2019-02-14 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20190210_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
