# Generated by Django 2.1.5 on 2019-02-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20190204_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radical',
            name='mnemonic_explanation',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
