# Generated by Django 2.1.7 on 2019-02-20 22:03

from django.db import migrations, models
import learning.models
import learning.storage


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_auto_20190213_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='small_color_coded',
            field=models.ImageField(default='default.jpg', storage=learning.storage.OverwriteFileSystemStorage(), upload_to=learning.models.PathAndRename('small_color_coded/C')),
        ),
    ]
