# Generated by Django 2.1.7 on 2019-06-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190505_1341'),
        ('accounts', '0002_auto_20190602_1835'),
    ]

    operations = [
    ]
