# Generated by Django 3.1.1 on 2021-02-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210212_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Used for resetting your password and receiving notifications.', max_length=254, null=True),
        ),
    ]
