# Generated by Django 2.2.1 on 2019-06-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190617_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_study_time',
            field=models.DateTimeField(null=True),
        ),
    ]
