# Generated by Django 2.1.7 on 2019-06-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_last_study_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_study_date',
        ),
    ]
