# Generated by Django 3.1.1 on 2021-02-21 09:36
import logging
from django.db import migrations


def forward(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    emails = set()
    for user in User.objects.all():
        if user.email != '':
            if user.email in emails:
                logging.info(f"remove email from {repr(user)}")
                user.email = None
                user.save()
            emails.add(user.email)
        else:
            user.email = None
            user.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210221_0941'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
