# Generated by Django 2.2.1 on 2019-06-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20190602_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_study_date',
            field=models.DateField(null=True),
        ),
    ]
