# Generated by Django 2.2.1 on 2019-06-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190605_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_study_vocab_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
