# Generated by Django 2.1.7 on 2019-08-11 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_last_study_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_study_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_study_vocab_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercharacter',
            name='time_last_learned',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
