# Generated by Django 3.1.1 on 2021-02-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210221_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-last_login',)},
        ),
    ]
