# Generated by Django 3.1.1 on 2021-04-07 07:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210224_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='This is the name displayed to others. We recommend using your real name. Leave blank to use your username. You may change this later.', max_length=30, validators=[accounts.models.DisplayNameValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Used for resetting your password and receiving notifications. This could also be used for login.', max_length=254, null=True, unique=True),
        ),
    ]
