# Generated by Django 3.1.1 on 2020-09-30 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_auto_20200929_1152'),
        ('accounts', '0007_auto_20200828_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercharactertag',
            name='character_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_character_tags', related_query_name='user_character_tag', to='learning.characterset'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usercharactertag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usercharactertag',
            name='name',
        ),
    ]
