# Generated by Django 3.1.1 on 2021-04-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210407_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(blank=True, help_text='can be seen by jiezi staff only', max_length=30),
        ),
    ]
