# Generated by Django 2.2.1 on 2019-06-15 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_last_study_vocab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_study_vocab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learning.Character'),
        ),
    ]
