# Generated by Django 2.2.1 on 2019-06-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190615_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_study_vocab',
        ),
    ]
