# Generated by Django 3.1.1 on 2020-09-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_auto_20200929_1152'),
        ('accounts', '0008_auto_20200930_0948'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercharactertag',
            unique_together={('user', 'character_set')},
        ),
    ]
