# Generated by Django 3.1.1 on 2020-10-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200930_1153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercharactertag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercharactertag',
            name='character_set',
        ),
        migrations.RemoveField(
            model_name='usercharactertag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercharactertag',
            name='user_characters',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cn_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_study_duration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_study_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_study_vocab_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='study_streak',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_study_duration',
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserCharacter',
        ),
        migrations.DeleteModel(
            name='UserCharacterTag',
        ),
    ]
