# Generated by Django 2.2.1 on 2019-06-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_last_study_vocab'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_study_time',
            field=models.DateTimeField(null=True),
        ),
    ]
