# Generated by Django 3.1.1 on 2020-10-13 07:10

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201013_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='This is the name displayed to others. We recommend using your real name.', max_length=30, validators=[django.core.validators.MinLengthValidator(4), accounts.models.DisplayNameValidator]),
        ),
    ]
