# Generated by Django 3.1.1 on 2020-10-13 08:57

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201013_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='This is the name displayed to others. We recommend using your real name. You may change this later.', max_length=30, validators=[django.core.validators.MinLengthValidator(4), accounts.models.DisplayNameValidator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Your email is used for resetting password and receiving notifications', max_length=254),
        ),
    ]
