# Generated by Django 3.1.1 on 2020-10-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201017_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-time']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent_time',
            new_name='time',
        ),
    ]
