# Generated by Django 3.1.1 on 2020-11-01 10:12

from django.db import migrations


def update(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        if user.is_guest:
            user.display_name = 'Guest'
        elif not user.display_name:
            user.display_name = user.username
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201101_1012'),
    ]

    operations = [
        migrations.RunPython(update)
    ]
