# Generated by Django 3.1.1 on 2021-02-12 06:53

from django.db import migrations, models
import django.db.models.deletion
import jiezi.utils.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0056_radical_is_learnable'),
        ('accounts', '0002_auto_20210212_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=100, verbose_name='Class name')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher', serialize=False, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to='accounts.user')),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', related_query_name='student', to='classroom.class')),
            ],
            bases=(jiezi.utils.mixins.StrDefaultReprMixin, models.Model),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', related_query_name='class', to='classroom.teacher'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', related_query_name='assignment', to='classroom.class')),
                ('wordset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', related_query_name='assignment', to='content.wordset')),
            ],
            options={
                'ordering': ['-last_modified_time'],
                'unique_together': {('klass', 'wordset')},
            },
        ),
    ]
