# Generated by Django 3.1.1 on 2021-03-26 07:06

from django.db import migrations, models
from django.utils.crypto import get_random_string


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_assignment_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='uuid',
        ),
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.SlugField(blank=True),
        ),
    ]
