# Generated by Django 3.1.1 on 2021-03-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20210326_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.SlugField(unique=True),
        ),
    ]
