# Generated by Django 3.1.1 on 2020-10-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20201012_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school_name',
            field=models.CharField(default='NOT_SET', max_length=200),
            preserve_default=False,
        ),
    ]
