# Generated by Django 3.1.1 on 2020-10-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_teacher_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='school_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.CharField(blank=True, help_text='Please also include the region / country', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_description',
            field=models.TextField(blank=True, help_text='You may include the curriculum that your school uses, orthe age ranage of your students', max_length=2000, verbose_name='Please describe your school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='wechat_id',
            field=models.CharField(blank=True, help_text='Optional, if applicable', max_length=40),
        ),
    ]
