# Generated by Django 3.1.1 on 2021-07-02 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0072_auto_20210630_0457'),
        ('classroom', '0006_teacher_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(default='NOT SET', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='WordInAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField(default=99, help_text='This determines the order of the elements')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.assignment')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.word')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('word', 'assignment', 'order')},
            },
        ),
        migrations.CreateModel(
            name='RadicalInAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField(default=99, help_text='This determines the order of the elements')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.assignment')),
                ('radical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.radical')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('radical', 'assignment', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CharacterInAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField(default=99, help_text='This determines the order of the elements')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.assignment')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.character')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('character', 'assignment', 'order')},
            },
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='wordset',
        ),
        migrations.AddField(
            model_name='assignment',
            name='characters',
            field=models.ManyToManyField(through='classroom.CharacterInAssignment', to='content.Character'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='radicals',
            field=models.ManyToManyField(through='classroom.RadicalInAssignment', to='content.Radical'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='words',
            field=models.ManyToManyField(through='classroom.WordInAssignment', to='content.Word'),
        ),
    ]
