# Generated by Django 3.1.1 on 2020-10-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20201013_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.CharField(blank=True, help_text='Please also include the region / country. For example,\n                "St. Mark\'s School, Massachusetts, United States" ', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school_description',
            field=models.TextField(blank=True, help_text='You may include the curriculum that your school uses\n        (E.g. Integrated Chinese, IB curriculum, HSK Standard Course, etc.\n        ) ', max_length=2000, verbose_name='Please describe your school'),
        ),
    ]
