# Generated by Django 3.1.1 on 2021-07-02 16:49

from django.db import migrations


def forward(apps, schema_editor):
    Class = apps.get_model('classroom', 'Class')
    for klass in Class.objects.all():
        klass.assignments.all().delete()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20210702_1649'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
