# Generated by Django 3.1.1 on 2021-07-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20210702_1649'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('klass', 'name')},
        ),
    ]
