# Generated by Django 3.1.1 on 2020-10-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20201028_0837_squashed_0007_delete_reviewmanager'),
        ('classroom', '0009_assignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('in_class', 'character_set')},
        ),
    ]
