# Generated by Django 3.1.1 on 2021-08-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20210813_1548'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('teacher', 'name')},
        ),
    ]
