# Generated by Django 2.1.7 on 2019-04-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('chinese', models.CharField(max_length=1)),
                ('pinyin', models.CharField(max_length=6)),
                ('part_of_speech_1', models.CharField(max_length=50)),
                ('definition_1', models.CharField(max_length=50)),
                ('part_of_speech_2', models.CharField(max_length=50)),
                ('definition_2', models.CharField(blank=True, max_length=50, null=True)),
                ('explanation_2', models.CharField(blank=True, max_length=200, null=True)),
                ('part_of_speech_3', models.CharField(max_length=50)),
                ('definition_3', models.CharField(blank=True, max_length=50, null=True)),
                ('explanation_3', models.CharField(blank=True, max_length=200, null=True)),
                ('radical_1_id', models.IntegerField()),
                ('radical_2_id', models.IntegerField(blank=True, null=True)),
                ('radical_3_id', models.IntegerField(blank=True, null=True)),
                ('mnemonic_explanation', models.TextField(max_length=200)),
                ('example_1_word', models.CharField(max_length=5)),
                ('example_1_pinyin', models.CharField(max_length=25)),
                ('example_1_character', models.CharField(max_length=50)),
                ('example_1_meaning', models.CharField(max_length=50)),
                ('example_2_word', models.CharField(blank=True, max_length=5, null=True)),
                ('example_2_pinyin', models.CharField(blank=True, max_length=25, null=True)),
                ('example_2_character', models.CharField(blank=True, max_length=50, null=True)),
                ('example_2_meaning', models.CharField(blank=True, max_length=50, null=True)),
                ('is_preview_definition', models.BooleanField()),
                ('is_preview_pinyin', models.BooleanField()),
                ('color_coded_image', models.ImageField(default='default.jpg', upload_to='')),
                ('stroke_order_image', models.ImageField(default='default.jpg', upload_to='')),
                ('small_color_coded', models.ImageField(default='default.jpg', upload_to='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('characters', models.ManyToManyField(to='learning.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Radical',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('chinese', models.CharField(max_length=1)),
                ('pinyin', models.CharField(max_length=10)),
                ('definition', models.CharField(max_length=50)),
                ('mnemonic_explanation', models.TextField(blank=True, max_length=100, null=True)),
                ('mnemonic_image', models.ImageField(default='default.jpg', upload_to='')),
                ('is_phonetic', models.BooleanField()),
                ('is_semantic', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='radicals',
            field=models.ManyToManyField(related_name='characters', related_query_name='character', to='learning.Radical'),
        ),
    ]
