# Generated by Django 2.1.7 on 2019-06-22 20:36

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
