# Generated by Django 2.1.7 on 2019-07-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20190622_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='definition_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='definition_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='definition_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='explanation_2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='explanation_3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='mnemonic_explanation',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='character',
            name='pinyin',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='radical',
            name='definition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='radical',
            name='mnemonic_explanation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='radical',
            name='pinyin',
            field=models.CharField(max_length=15),
        ),
    ]
