# Generated by Django 3.1.1 on 2021-02-07 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0056_radical_is_learnable'),
        ('learning', '0002_auto_20210206_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterField(
            model_name='record',
            name='reviewable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.reviewableobject'),
        ),
    ]
