# Generated by Django 3.1.1 on 2021-02-14 03:07

from django.db import migrations


def forward(apps, schema_editor):
    LearningProcess = apps.get_model('learning', 'LearningProcess')
    for process in LearningProcess.objects.all():
        process.data.setdefault('stats', {
            'correct_answer': 0,
            'wrong_answer': 0,
        })
        process.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20210207_0645'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
