# Generated by Django 2.1.7 on 2019-05-01 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20190412_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='small_color_coded',
        ),
    ]
