# Generated by Django 3.1.1 on 2021-04-11 08:31

import logging
from django.db import migrations


def forward(apps, schema_editor):
    UserReviewable = apps.get_model('learning', 'UserReviewable')
    s = set()
    for ur in UserReviewable.objects.all():
        pair = (ur.user, ur.reviewable)
        if pair in s:
            logging.warning("%r duplicate, removing", ur)
            ur.delete()
        else:
            s.add(pair)


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20210214_0307'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
