# Generated by Django 2.1.7 on 2019-11-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_character_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radical',
            name='chinese',
            field=models.CharField(max_length=3),
        ),
    ]
