# Generated by Django 2.1.7 on 2020-08-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_auto_20191114_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radical',
            name='chinese',
            field=models.CharField(max_length=6),
        ),
    ]
