# Generated by Django 3.1.1 on 2021-04-11 08:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0067_auto_20210326_0641'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0005_remove_duplicate_userrevieable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreviewable',
            unique_together={('user', 'reviewable')},
        ),
    ]
