# Generated by Django 2.1.7 on 2020-09-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20200828_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='color_coded_image',
        ),
    ]
