# Generated by Django 3.1.1 on 2020-09-29 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20200918_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='radical_1_id',
        ),
        migrations.RemoveField(
            model_name='character',
            name='radical_2_id',
        ),
        migrations.RemoveField(
            model_name='character',
            name='radical_3_id',
        ),
        migrations.AddField(
            model_name='character',
            name='radical_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learning.radical'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='radical_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learning.radical'),
        ),
        migrations.AddField(
            model_name='character',
            name='radical_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learning.radical'),
        ),
        migrations.AlterField(
            model_name='characterset',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
