# Generated by Django 3.1.1 on 2020-10-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_auto_20200929_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='explanation_2',
        ),
        migrations.RemoveField(
            model_name='character',
            name='explanation_3',
        ),
    ]
