# Generated by Django 3.1.1 on 2020-10-10 12:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import jiezi.utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('accounts', '0010_auto_20201010_1216'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
        ('learning', '0009_auto_20200929_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProcess',
            fields=[
                ('state', django_fsm.FSMIntegerField(default=10, verbose_name=[(10, '_decide'), (20, '_start_learn'), (30, 'done_learn'), (40, 'start_relearn'), (50, 'done_relearn'), (60, 'tolerant_review'), (70, 'test_review'), (80, '_finish')])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='learning_process', serialize=False, to='classroom.student')),
                ('review_field_index', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)])),
                ('review_answer_index', models.PositiveSmallIntegerField(default=0)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.character')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinyin_in_a_row', models.IntegerField(default=0)),
                ('pinyin_in_a_row_required', models.IntegerField(default=2)),
                ('pinyin_mastered', models.BooleanField(default=False)),
                ('pinyin_time_last_studied', models.DateTimeField(auto_now_add=True)),
                ('definition_1_in_a_row', models.IntegerField(default=0)),
                ('definition_1_in_a_row_required', models.IntegerField(default=2)),
                ('definition_1_mastered', models.BooleanField(default=False)),
                ('definition_1_time_last_studied', models.DateTimeField(auto_now_add=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(10, 'To Learn'), (20, 'In Progress'), (30, 'Mastered')], default=10)),
                ('time_added', models.DateField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_characters', related_query_name='student_character', to='content.character')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_characters', related_query_name='student_character', to='classroom.student')),
            ],
            options={
                'ordering': ['-state'],
                'unique_together': {('student', 'character')},
            },
            bases=(models.Model, jiezi.utils.mixins.StrDefaultReprMixin),
        ),
        migrations.CreateModel(
            name='StudentCharacterTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_tags', related_query_name='sc_tag', to='content.characterset')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_tags', related_query_name='sc_tag', to=settings.AUTH_USER_MODEL)),
                ('student_characters', models.ManyToManyField(related_name='sc_tags', related_query_name='sc_tag', to='learning.StudentCharacter')),
            ],
            options={
                'unique_together': {('student', 'character_set')},
            },
        ),
        migrations.RemoveField(
            model_name='character',
            name='radical_1',
        ),
        migrations.RemoveField(
            model_name='character',
            name='radical_2',
        ),
        migrations.RemoveField(
            model_name='character',
            name='radical_3',
        ),
        migrations.RemoveField(
            model_name='characterset',
            name='characters',
        ),
        migrations.DeleteModel(
            name='Radical',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='CharacterSet',
        ),
        migrations.AddField(
            model_name='learningprocess',
            name='sc_tags',
            field=models.ManyToManyField(related_name='_learningprocess_sc_tags_+', to='learning.StudentCharacterTag'),
        ),
    ]
