# Generated by Django 3.1.1 on 2020-10-11 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('learning', '0010_auto_20201010_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcharactertag',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_tags', related_query_name='sc_tag', to='classroom.student'),
        ),
    ]
