# Generated by Django 3.1.1 on 2020-10-12 08:01

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_auto_20201011_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcharacter',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(10, 'To Learn'), (20, 'In Progress'), (30, 'Mastered')], default=10),
        ),
    ]
