# Generated by Django 3.1.1 on 2020-10-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_auto_20201010_1308'),
        ('learning', '0016_auto_20201012_1138'),
    ]

    operations = [
    ]
