# Generated by Django 3.1.1 on 2020-10-19 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_reviewmanager'),
        ('learning', '0016_auto_20201012_1138'),
    ]

    operations = [
    ]
