# Generated by Django 3.1.1 on 2020-10-29 15:34

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import learning.models.review_manager


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# learning.migrations.0022_auto_20201029_0813
# learning.migrations.0023_auto_20201029_0835

def update_SCA(apps, schema_editor):
    StudentCharacter = apps.get_model('learning', 'StudentCharacter')
    SCAbility = apps.get_model('learning', 'SCAbility')
    Ability = apps.get_model('learning', 'Ability')
    for sc in StudentCharacter.objects.all():
        for ability in Ability.objects.all():
            # signal not active during migration so have to manually set
            sca = SCAbility.objects.create(student_character=sc,
                                           ability=ability,
                                           student=sc.student,
                                           character=sc.character)
            if sc.state == StudentCharacter.MASTERED:
                sca.state = SCAbility.MASTERED
                sca.save()


def update_review_manager(apps, schema_editor):
    ReviewManager = apps.get_model('learning', 'ReviewManager')
    LearningProcess = apps.get_model('learning', 'LearningProcess')
    for lp in LearningProcess.objects.all():
        lp.delete()
    for rm in ReviewManager.objects.all():
        rm.delete()


class Migration(migrations.Migration):

    replaces = [('learning', '0018_auto_20201028_0837'), ('learning', '0019_auto_20201029_0652'), ('learning', '0020_auto_20201029_0754'), ('learning', '0021_auto_20201029_0759'), ('learning', '0022_auto_20201029_0813'), ('learning', '0023_auto_20201029_0835'), ('learning', '0024_learningprocess_review_ability'), ('learning', '0025_auto_20201029_1133'), ('learning', '0026_remove_scability_mastered'), ('learning', '0027_learningprocess_review_tested_abilities')]

    dependencies = [
        ('learning', '0017_learningprocess_review_manager'),
        ('content', '0004_auto_20201028_0837'),
        ('classroom', '0008_auto_20201015_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, 'definition'), (1, 'form'), (2, 'pronunciation')], unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='studentcharacter',
            options={},
        ),
        migrations.RemoveField(
            model_name='learningprocess',
            name='review_answer_index',
        ),
        migrations.RemoveField(
            model_name='learningprocess',
            name='review_field_index',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='definition_1_in_a_row',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='definition_1_in_a_row_required',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='definition_1_mastered',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='definition_1_time_last_studied',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='pinyin_in_a_row',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='pinyin_in_a_row_required',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='pinyin_mastered',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='pinyin_time_last_studied',
        ),
        migrations.AddField(
            model_name='studentcharacter',
            name='time_last_studied',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='learningprocess',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(10, 'decide'), (20, 'start_learn'), (30, 'done_learn'), (40, 'start_relearn'), (50, 'done_relearn'), (60, 'tolerant_review_1'), (61, 'tolerant_review_2'), (70, 'test_review'), (80, 'finish')], default=10),
        ),
        migrations.CreateModel(
            name='SCAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMIntegerField(choices=[(10, 'To Learn'), (20, 'In Progress'), (30, 'Mastered')], default=10)),
                ('in_a_row', models.IntegerField(default=0)),
                ('in_a_row_required', models.IntegerField(default=2)),
                ('time_last_studied', models.DateTimeField(auto_now=True)),
                ('mastered', models.BooleanField(default=False)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scas', related_query_name='sca', to='learning.ability')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scas', related_query_name='sca', to='content.character')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scas', related_query_name='sca', to='classroom.student')),
                ('student_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scas', related_query_name='sca', to='learning.studentcharacter')),
            ],
            options={
                'unique_together': {('student', 'character', 'ability')},
            },
        ),
        migrations.CreateModel(
            name='ReviewManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_DefinitionMCAnswerField', models.BooleanField(default=True)),
                ('use_DefinitionMCAnswerCharacter', models.BooleanField(default=True)),
                ('use_PinyinMC', models.BooleanField(default=True)),
                ('use_DefinitionTOF', models.BooleanField(default=True)),
                ('use_PinyinTOF', models.BooleanField(default=True)),
                ('use_DefinitionFITB', models.BooleanField(default=True)),
                ('use_PinyinFITB', models.BooleanField(default=True)),
                ('monitored_abilities', models.ManyToManyField(related_name='_reviewmanager_monitored_abilities_+', related_query_name='+', to='learning.Ability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='learningprocess',
            name='review_manager',
            field=models.ForeignKey(default=learning.models.review_manager.ReviewManager.get_default_pk, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='learning.reviewmanager'),
        ),
        migrations.RunPython(
            update_SCA
        ),
        migrations.RunPython(
            update_review_manager
        ),
        migrations.AddField(
            model_name='learningprocess',
            name='review_ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='learning.ability'),
        ),
        migrations.AlterField(
            model_name='reviewmanager',
            name='monitored_abilities',
            field=models.ManyToManyField(related_name='_reviewmanager_monitored_abilities_+', to='learning.Ability'),
        ),
        migrations.RemoveField(
            model_name='scability',
            name='mastered',
        ),
        migrations.AddField(
            model_name='learningprocess',
            name='review_tested_abilities',
            field=models.ManyToManyField(related_name='_learningprocess_review_tested_abilities_+', to='learning.Ability'),
        ),
    ]
