# Generated by Django 3.1.1 on 2020-10-28 08:37

import content.reviews
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20201028_0837'),
        ('learning', '0017_learningprocess_review_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningprocess',
            name='review_manager',
            field=models.ForeignKey(default=content.reviews.ReviewManager.get_default_pk, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.reviewmanager'),
        ),
    ]
