# Generated by Django 3.1.1 on 2020-10-29 06:52

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20201015_1322'),
        ('content', '0004_auto_20201028_0837'),
        ('learning', '0018_auto_20201028_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, 'definition'), (1, 'form'), (2, 'pronunciation')], unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='studentcharacter',
            options={},
        ),
        migrations.RemoveField(
            model_name='learningprocess',
            name='review_answer_index',
        ),
        migrations.RemoveField(
            model_name='learningprocess',
            name='review_field_index',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='definition_1_in_a_row',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='definition_1_in_a_row_required',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='definition_1_mastered',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='definition_1_time_last_studied',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='pinyin_in_a_row',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='pinyin_in_a_row_required',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='pinyin_mastered',
        ),
        migrations.RemoveField(
            model_name='studentcharacter',
            name='pinyin_time_last_studied',
        ),
        migrations.AddField(
            model_name='studentcharacter',
            name='time_last_studied',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='learningprocess',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(10, 'decide'), (20, 'start_learn'), (30, 'done_learn'), (40, 'start_relearn'), (50, 'done_relearn'), (60, 'tolerant_review_1'), (61, 'tolerant_review_2'), (70, 'test_review'), (80, 'finish')], default=10),
        ),
        migrations.CreateModel(
            name='SCAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMIntegerField(choices=[(10, 'To Learn'), (20, 'In Progress'), (30, 'Mastered')], default=10)),
                ('in_a_row', models.IntegerField(default=0)),
                ('in_a_row_required', models.IntegerField(default=2)),
                ('time_last_studied', models.DateTimeField(auto_now=True)),
                ('mastered', models.BooleanField(default=False)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scas', related_query_name='sca', to='learning.ability')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scas', related_query_name='sca', to='content.character')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scas', related_query_name='sca', to='classroom.student')),
                ('student_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scas', related_query_name='sca', to='learning.studentcharacter')),
            ],
            options={
                'unique_together': {('student', 'character', 'ability')},
            },
        ),
    ]
