# Generated by Django 3.1.1 on 2020-10-29 17:04

from django.db import migrations


def update(apps, schema_editor):
    StudentCharacter = apps.get_model('learning', 'StudentCharacter')
    SCAbility = apps.get_model('learning', 'SCAbility')
    Ability = apps.get_model('learning', 'Ability')
    ReviewManager = apps.get_model('learning', 'ReviewManager')
    LearningProcess = apps.get_model('learning', 'LearningProcess')
    for sc in StudentCharacter.objects.all():
        for ability in Ability.objects.all():
            # signal not active during migration so have to manually set
            sca = SCAbility.objects.get_or_create(student_character=sc,
                ability=ability, student=sc.student, character=sc.character)[0]
            if sc.state == 30: # MASTERED
                sca.state = 30 # MASTERED
                sca.save()
    for lp in LearningProcess.objects.all():
        lp.delete()
    for rm in ReviewManager.objects.all():
        rm.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_auto_20201028_0837_squashed_0027_learningprocess_review_tested_abilities'),
    ]

    operations = [
        migrations.RunPython(update)
    ]
