# Generated by Django 3.1.1 on 2020-10-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_data_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcharactertag',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
