# Generated by Django 3.1.1 on 2020-10-31 14:27

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_studentcharactertag_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcharacter',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(20, 'In Progress'), (30, 'Mastered'), (10, 'To Learn')], default=10),
        ),
    ]
