# Generated by Django 3.1.1 on 2020-10-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_auto_20201029_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmanager',
            name='monitored_abilities',
            field=models.ManyToManyField(related_name='_reviewmanager_monitored_abilities_+', related_query_name='+', to='learning.Ability'),
        ),
    ]
