# Generated by Django 3.1.1 on 2020-10-29 08:13

from django.db import migrations


def update_SCA(apps, schema_editor):
    StudentCharacter = apps.get_model('learning', 'StudentCharacter')
    SCAbility = apps.get_model('learning', 'SCAbility')
    Ability = apps.get_model('learning', 'Ability')
    for sc in StudentCharacter.objects.all():
        for ability in Ability.objects.all():
            # signal not active during migration so have to manually set
            sca = SCAbility.objects.create(student_character=sc,
                                           ability=ability,
                                           student=sc.student,
                                           character=sc.character)
            if sc.state == StudentCharacter.MASTERED:
                sca.state = SCAbility.MASTERED
                sca.save()


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_auto_20201029_0759'),
    ]

    operations = [
        migrations.RunPython(update_SCA),
    ]
