# Generated by Django 3.1.1 on 2020-11-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('learning', '0022_auto_20201102_0801'), ('learning', '0023_auto_20201102_0802'), ('learning', '0024_auto_20201102_0956')]

    dependencies = [
        ('learning', '0021_auto_20201031_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='scability',
            name='correct_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scability',
            name='total_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentcharacter',
            name='correct_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentcharacter',
            name='total_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scability',
            name='accuracy',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AddField(
            model_name='studentcharacter',
            name='accuracy',
            field=models.FloatField(default=float("nan")),
        ),
    ]
