# Generated by Django 3.1.1 on 2020-10-29 08:35

from django.db import migrations

def update_review_manager(apps, schema_editor):
    ReviewManager = apps.get_model('learning', 'ReviewManager')
    LearningProcess = apps.get_model('learning', 'LearningProcess')
    for lp in LearningProcess.objects.all():
        lp.delete()
    for rm in ReviewManager.objects.all():
        rm.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_auto_20201029_0813'),
    ]

    operations = [
        migrations.RunPython(update_review_manager),
    ]
