# Generated by Django 3.1.1 on 2020-10-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_auto_20201029_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprocess',
            name='review_ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='learning.ability'),
        ),
    ]
