# Generated by Django 3.1.1 on 2020-11-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_auto_20201106_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scability',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentcharacter',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
    ]
