# Generated by Django 3.1.1 on 2020-10-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_learningprocess_review_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmanager',
            name='monitored_abilities',
            field=models.ManyToManyField(related_name='_reviewmanager_monitored_abilities_+', to='learning.Ability'),
        ),
    ]
