# Generated by Django 3.1.1 on 2020-11-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_auto_20201110_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmanager',
            name='use_PinyinFITB',
        ),
    ]
