# Generated by Django 3.1.1 on 2020-10-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_auto_20201029_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scability',
            name='mastered',
        ),
    ]
