# Generated by Django 3.1.1 on 2020-10-10 12:16

import content.models
from django.db import migrations, models
import django.db.models.deletion
import jiezi.utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(max_length=1)),
                ('pinyin', models.CharField(max_length=15)),
                ('part_of_speech_1', models.CharField(max_length=50)),
                ('definition_1', models.CharField(max_length=100)),
                ('part_of_speech_2', models.CharField(blank=True, max_length=50, null=True)),
                ('definition_2', models.CharField(blank=True, max_length=100, null=True)),
                ('explanation_2', models.CharField(blank=True, max_length=300, null=True)),
                ('part_of_speech_3', models.CharField(blank=True, max_length=50, null=True)),
                ('definition_3', models.CharField(blank=True, max_length=100, null=True)),
                ('explanation_3', models.CharField(blank=True, max_length=300, null=True)),
                ('mnemonic_explanation', models.CharField(max_length=800)),
                ('example_1_word', models.CharField(max_length=10)),
                ('example_1_pinyin', models.CharField(max_length=25)),
                ('example_1_character', models.CharField(max_length=100)),
                ('example_1_meaning', models.CharField(max_length=100)),
                ('example_2_word', models.CharField(blank=True, max_length=10, null=True)),
                ('example_2_pinyin', models.CharField(blank=True, max_length=25, null=True)),
                ('example_2_character', models.CharField(blank=True, max_length=100, null=True)),
                ('example_2_meaning', models.CharField(blank=True, max_length=100, null=True)),
                ('is_preview_definition', models.BooleanField()),
                ('is_preview_pinyin', models.BooleanField()),
                ('structure', models.IntegerField(null=True)),
                ('stroke_order_image', models.ImageField(default='default.jpg', upload_to='')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(models.Model, content.models.DFModelMixin, jiezi.utils.mixins.StrDefaultReprMixin),
        ),
        migrations.CreateModel(
            name='Radical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(max_length=6)),
                ('pinyin', models.CharField(max_length=15)),
                ('definition', models.CharField(max_length=100)),
                ('mnemonic_explanation', models.CharField(blank=True, max_length=300, null=True)),
                ('mnemonic_image', models.ImageField(default='default.jpg', upload_to='')),
                ('is_phonetic', models.BooleanField()),
                ('is_semantic', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(models.Model, content.models.DFModelMixin, jiezi.utils.mixins.StrDefaultReprMixin),
        ),
        migrations.CreateModel(
            name='CharacterSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('characters', models.ManyToManyField(to='content.Character')),
            ],
            bases=(models.Model, content.models.DFModelMixin, jiezi.utils.mixins.StrDefaultReprMixin),
        ),
        migrations.AddField(
            model_name='character',
            name='radical_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.radical'),
        ),
        migrations.AddField(
            model_name='character',
            name='radical_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.radical'),
        ),
        migrations.AddField(
            model_name='character',
            name='radical_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.radical'),
        ),
    ]
