# Generated by Django 3.1.1 on 2020-12-21 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definitioninword',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='character',
            name='definitions',
        ),
        migrations.AddField(
            model_name='definitioninword',
            name='order',
            field=models.SmallIntegerField(default=0, help_text='This determines the order of the definitions.'),
        ),
        migrations.AlterField(
            model_name='character',
            name='memory_aid',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='character',
            name='note',
            field=models.TextField(blank=True, help_text='This is for internal use only, feel free to use it for note taking', max_length=500),
        ),
        migrations.AlterField(
            model_name='characterinword',
            name='order',
            field=models.SmallIntegerField(help_text='This determines the order of the character in the word.'),
        ),
        migrations.AlterField(
            model_name='radical',
            name='note',
            field=models.TextField(blank=True, help_text='This is for internal use only, feel free to use it for note taking', max_length=500),
        ),
        migrations.AlterField(
            model_name='word',
            name='note',
            field=models.TextField(blank=True, help_text='This is for internal use only, feel free to use it for note taking', max_length=500),
        ),
        migrations.CreateModel(
            name='DefinitionInCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0, help_text='This determines the order of the definitions.')),
                ('definition', models.CharField(max_length=70)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', related_query_name='definition', to='content.character')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
