# Generated by Django 3.1.1 on 2020-10-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='explanation_2',
        ),
        migrations.RemoveField(
            model_name='character',
            name='explanation_3',
        ),
    ]
