# Generated by Django 3.1.1 on 2020-12-21 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20201221_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordInSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='This determines the order of the word in the set.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='character',
            name='radicals',
            field=models.ManyToManyField(related_name='characters', related_query_name='character', through='content.RadicalInCharacter', to='content.Radical'),
        ),
        migrations.AlterField(
            model_name='word',
            name='characters',
            field=models.ManyToManyField(related_name='words', related_query_name='word', through='content.CharacterInWord', to='content.Character'),
        ),
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='This is for internal use only, feel free to use it for note taking', max_length=500)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('words', models.ManyToManyField(related_name='word_sets', related_query_name='word_set', through='content.WordInSet', to='content.Word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wordinset',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.word'),
        ),
        migrations.AddField(
            model_name='wordinset',
            name='word_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.wordset'),
        ),
        migrations.AlterUniqueTogether(
            name='wordinset',
            unique_together={('word', 'word_set')},
        ),
    ]
