# Generated by Django 3.1.1 on 2020-10-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20201010_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ("use_<class 'content.reviews.DefinitionMCAnswerField'>", models.BooleanField(default=True)),
                ("use_<class 'content.reviews.DefinitionMCAnswerCharacter'>", models.BooleanField(default=True)),
                ("use_<class 'content.reviews.PinyinMC'>", models.BooleanField(default=True)),
                ("use_<class 'content.reviews.DefinitionTOF'>", models.BooleanField(default=True)),
                ("use_<class 'content.reviews.PinyinTOF'>", models.BooleanField(default=True)),
                ("use_<class 'content.reviews.DefinitionFITB'>", models.BooleanField(default=True)),
                ("use_<class 'content.reviews.PinyinFITB'>", models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
