# Generated by Django 3.1.1 on 2020-10-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('content', '0004_auto_20201028_0837'), ('content', '0005_reviewmanager_monitored_abilities'), ('content', '0006_auto_20201029_0759'), ('content', '0007_delete_reviewmanager')]

    dependencies = [
        ('content', '0003_reviewmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewManager',
        ),
    ]
