# Generated by Django 3.1.1 on 2020-11-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20201028_0837_squashed_0007_delete_reviewmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadicalInCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radical_loc', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.character')),
                ('radical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.radical')),
            ],
            options={
                'ordering': ['radical_loc'],
                'unique_together': {('character', 'radical')},
            },
        ),
        migrations.AddField(
            model_name='character',
            name='radicals',
            field=models.ManyToManyField(related_name='characters', related_query_name='character', through='content.RadicalInCharacter', to='content.Radical'),
        ),
    ]
