# Generated by Django 3.1.1 on 2020-12-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20201221_0503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='sentence',
            name='order',
            field=models.SmallIntegerField(default=0, help_text='This determines the order of the sentence in word.'),
        ),
    ]
