# Generated by Django 3.1.1 on 2020-10-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_auto_20201029_0652'),
        ('content', '0004_auto_20201028_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmanager',
            name='monitored_abilities',
            field=models.ManyToManyField(related_name='_reviewmanager_monitored_abilities_+', to='learning.Ability'),
        ),
    ]
