# Generated by Django 3.1.1 on 2020-11-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20201120_1253'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='radicalincharacter',
            unique_together={('character', 'radical', 'radical_loc')},
        ),
    ]
