# Generated by Django 3.1.1 on 2020-12-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20201221_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='radical',
            name='explanation',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='radical',
            name='pinyin',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='radical',
            name='definition',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
