# Generated by Django 3.1.1 on 2020-10-29 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20201029_0759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewManager',
        ),
    ]
