# Generated by Django 3.1.1 on 2020-12-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20201221_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='radical',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='radical_image/'),
        ),
        migrations.AddField(
            model_name='radicalincharacter',
            name='radical_type',
            field=models.CharField(choices=[(None, 'TODO'), ('semantic', 'semantic'), ('phonetic', 'phonetic'), ('both', 'both'), ('neither', 'neither')], default='TODO', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='character_type',
            field=models.CharField(blank=True, choices=[(None, 'TODO'), ('Ideographic', 'Ideographic'), ('Compound Ideographic', 'Compound Ideographic'), ('Picto-phonetic', 'Picto-phonetic'), ('Loan', 'Loan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='memory_aid',
            field=models.TextField(blank=True, default='TODO', max_length=300),
        ),
        migrations.AlterField(
            model_name='character',
            name='pinyin',
            field=models.CharField(default='TODO', max_length=20),
        ),
        migrations.AlterField(
            model_name='definitioninword',
            name='definition',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='definitioninword',
            name='part_of_speech',
            field=models.CharField(blank=True, choices=[(None, 'TODO'), ('adj', 'adjective'), ('adv', 'adverb'), ('conj', 'conjunction'), ('interj', 'interjection'), ('m', 'measure word'), ('mv', 'modal verb'), ('n', 'noun'), ('nu', 'numeral'), ('p', 'particle'), ('pn', 'proper noun'), ('pr', 'pronoun'), ('prefi', 'x prefi x'), ('prep', 'preposition'), ('qp', 'question particle'), ('qpr', 'question pronoun'), ('t', 'time word'), ('v', 'verb'), ('vc', 'verb plus complement'), ('vo', 'verb plus object')], max_length=6),
        ),
        migrations.AlterField(
            model_name='radical',
            name='definition',
            field=models.CharField(blank=True, default='TODO', max_length=100),
        ),
        migrations.AlterField(
            model_name='radical',
            name='explanation',
            field=models.TextField(blank=True, default='TODO', max_length=200),
        ),
        migrations.AlterField(
            model_name='radical',
            name='identifier',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='radical',
            name='pinyin',
            field=models.CharField(blank=True, default='TODO', max_length=20),
        ),
        migrations.AlterField(
            model_name='word',
            name='memory_aid',
            field=models.TextField(blank=True, default='TODO', max_length=300),
        ),
        migrations.AlterField(
            model_name='word',
            name='pinyin',
            field=models.CharField(default='TODO', max_length=36),
        ),
    ]
