# Generated by Django 3.1.1 on 2020-12-21 09:39

import content.models.radical
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20201221_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radical',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=content.models.radical.path_and_rename),
        ),
    ]
