# Generated by Django 3.1.1 on 2020-12-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20201221_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radical',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordset',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
