# Generated by Django 3.1.1 on 2020-12-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20201221_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicalincharacter',
            name='radical_type',
            field=models.CharField(blank=True, choices=[(None, 'TODO'), ('semantic', 'semantic'), ('phonetic', 'phonetic'), ('both', 'both'), ('neither', 'neither')], max_length=8),
        ),
    ]
