# Generated by Django 3.1.1 on 2020-12-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20201221_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterinword',
            name='order',
            field=models.FloatField(default=0, help_text='This determines the order of the elements'),
        ),
        migrations.AlterField(
            model_name='definitionincharacter',
            name='order',
            field=models.FloatField(default=0, help_text='This determines the order of the elements'),
        ),
        migrations.AlterField(
            model_name='definitioninword',
            name='order',
            field=models.FloatField(default=0, help_text='This determines the order of the elements'),
        ),
        migrations.AlterField(
            model_name='radicalincharacter',
            name='order',
            field=models.FloatField(default=0, help_text='This determines the order of the elements'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='order',
            field=models.FloatField(default=0, help_text='This determines the order of the elements'),
        ),
        migrations.AlterField(
            model_name='wordinset',
            name='order',
            field=models.FloatField(default=0, help_text='This determines the order of the elements'),
        ),
    ]
