# Generated by Django 3.1.1 on 2020-12-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_character_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='archive',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
