# Generated by Django 3.1.1 on 2020-12-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20201221_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='archive',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
