# Generated by Django 3.1.1 on 2020-12-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20201221_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='pinyin',
            field=models.CharField(default='TODO', max_length=40),
        ),
    ]
