# Generated by Django 3.1.1 on 2020-12-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20201221_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='archive',
            field=models.JSONField(blank=True, default=str),
        ),
    ]
