# Generated by Django 3.1.1 on 2020-12-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20201221_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicalincharacter',
            name='radical_type',
            field=models.CharField(blank=True, choices=[(None, 'TODO'), ('pictographic', 'pictographic'), ('semantic', 'semantic'), ('phonetic', 'phonetic'), ('both', 'both'), ('neither', 'neither')], max_length=12),
        ),
    ]
