# Generated by Django 3.1.1 on 2020-12-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20201227_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_type',
            field=models.CharField(blank=True, choices=[(None, 'TODO'), ('Pictographic', 'Pictographic'), ('Ideographic', 'Ideographic'), ('Compound Ideographic', 'Compound Ideographic'), ('Picto-phonetic', 'Picto-phonetic'), ('Loan', 'Loan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='memory_aid',
            field=models.TextField(blank=True, default='TODO', max_length=300, verbose_name='word memory aid'),
        ),
        migrations.AlterField(
            model_name='word',
            name='memory_aid',
            field=models.TextField(blank=True, default='TODO', max_length=300, verbose_name='word memory aid'),
        ),
    ]
