# Generated by Django 3.1.1 on 2021-01-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20201230_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='radical',
            name='archive',
            field=models.TextField(blank=True, help_text='This is autogenerated as reference', max_length=500),
        ),
        migrations.AddField(
            model_name='word',
            name='archive',
            field=models.TextField(blank=True, help_text='This is autogenerated as reference', max_length=500),
        ),
        migrations.AddField(
            model_name='wordset',
            name='archive',
            field=models.TextField(blank=True, help_text='This is autogenerated as reference', max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='archive',
            field=models.TextField(blank=True, help_text='This is autogenerated as reference', max_length=500),
        ),
    ]
