# Generated by Django 3.1.1 on 2021-01-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20210102_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='archive',
            field=models.TextField(blank=True, help_text='This is auto-generated as reference. Read-only', max_length=500),
        ),
        migrations.AlterField(
            model_name='radical',
            name='archive',
            field=models.TextField(blank=True, help_text='This is auto-generated as reference. Read-only', max_length=500),
        ),
        migrations.AlterField(
            model_name='word',
            name='archive',
            field=models.TextField(blank=True, help_text='This is auto-generated as reference. Read-only', max_length=500),
        ),
        migrations.AlterField(
            model_name='wordset',
            name='archive',
            field=models.TextField(blank=True, help_text='This is auto-generated as reference. Read-only', max_length=500),
        ),
    ]
