# Generated by Django 3.1.1 on 2021-01-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20210102_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='chinese',
            field=models.CharField(max_length=10),
        ),
    ]
