# Generated by Django 3.1.1 on 2021-01-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20210103_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definitioninword',
            name='definition',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
