# Generated by Django 3.1.1 on 2021-01-09 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('content', '0028_auto_20210105_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRAGQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_show_context', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FITBQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_show_context', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkedField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, max_length=20)),
                ('overwrite', models.CharField(blank=True, max_length=200)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewableObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewable', to='content.character')),
                ('radical', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewable', to='content.radical')),
                ('word', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewable', to='content.word')),
            ],
        ),
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_show_context', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=200)),
                ('num_choices', models.PositiveSmallIntegerField(default=4)),
                ('context_link', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.linkedfield')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(choices=[(0, 'Correct'), (100, 'Common Wrong'), (500, 'Missleading'), (2000, 'Very Missleading')], default=1)),
                ('linked_value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.linkedfield')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', related_query_name='choice', to='content.mcquestion')),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='GeneralQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DRAG', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_question', to='content.dragquestion')),
                ('FITB', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_question', to='content.fitbquestion')),
                ('MC', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_question', to='content.mcquestion')),
                ('reviewable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.reviewableobject')),
            ],
        ),
        migrations.AddField(
            model_name='fitbquestion',
            name='context_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.linkedfield'),
        ),
        migrations.AddField(
            model_name='dragquestion',
            name='context_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.linkedfield'),
        ),
    ]
