# Generated by Django 3.1.1 on 2021-01-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_auto_20210109_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcchoice',
            name='weight',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Correct'), (100, 'Common Wrong'), (500, 'Missleading'), (2000, 'Very Missleading')]),
        ),
    ]
