# Generated by Django 3.1.1 on 2021-01-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_auto_20210112_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragquestion',
            name='context_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.linkedfield'),
        ),
        migrations.AlterField(
            model_name='fitbquestion',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.linkedfield'),
        ),
        migrations.AlterField(
            model_name='fitbquestion',
            name='context_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.linkedfield'),
        ),
        migrations.AlterField(
            model_name='fitbquestion',
            name='extra_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.linkedfield'),
        ),
        migrations.AlterField(
            model_name='mcchoice',
            name='linked_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.linkedfield'),
        ),
        migrations.AlterField(
            model_name='mcchoice',
            name='weight',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Correct'), (100, 'Auto Common Wrong'), (101, 'Common Wrong'), (500, 'Missleading'), (2000, 'Very Missleading')]),
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='context_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.linkedfield'),
        ),
    ]
