# Generated by Django 3.1.1 on 2021-01-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20210113_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNDQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(blank=True, default='custom', max_length=20)),
                ('context_option', models.CharField(choices=[('NOT', 'Not show'), ('MUST', 'Must show'), ('AUTO', 'Auto')], default='AUTO', max_length=4)),
                ('question', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('context_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.linkedfield')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fitbquestion',
            name='must_show_context',
        ),
        migrations.RemoveField(
            model_name='generalquestion',
            name='DRAG',
        ),
        migrations.RemoveField(
            model_name='mcquestion',
            name='must_show_context',
        ),
        migrations.AddField(
            model_name='fitbquestion',
            name='context_option',
            field=models.CharField(choices=[('NOT', 'Not show'), ('MUST', 'Must show'), ('AUTO', 'Auto')], default='AUTO', max_length=4),
        ),
        migrations.AddField(
            model_name='mcquestion',
            name='context_option',
            field=models.CharField(choices=[('NOT', 'Not show'), ('MUST', 'Must show'), ('AUTO', 'Auto')], default='AUTO', max_length=4),
        ),
        migrations.DeleteModel(
            name='DRAGQuestion',
        ),
        migrations.AddField(
            model_name='generalquestion',
            name='CND',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_question', to='content.cndquestion'),
        ),
    ]
