# Generated by Django 3.1.1 on 2021-01-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_auto_20210114_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedfield',
            name='field_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
