# Generated by Django 3.1.1 on 2021-01-15 15:56

from django.db import migrations


def update(apps, schema_editor):
    DefinitionInWord = apps.get_model('content', 'DefinitionInWord')
    DefinitionInWord.objects.filter(part_of_speech='').update(part_of_speech=' ')


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_auto_20210115_1555'),
    ]

    operations = [
        migrations.RunPython(update)
    ]
