# Generated by Django 3.1.1 on 2021-01-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20210115_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='cndquestion',
            name='reviewable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.reviewableobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitbquestion',
            name='reviewable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.reviewableobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcquestion',
            name='reviewable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.reviewableobject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='memory_aid',
            field=models.TextField(blank=True, default='TODO', max_length=300, verbose_name='character memory aid'),
        ),
    ]
