# Generated by Django 3.1.1 on 2021-01-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_auto_20210118_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitbquestion',
            old_name='answer',
            new_name='answer_link',
        ),
        migrations.RenameField(
            model_name='fitbquestion',
            old_name='extra_information',
            new_name='title_link',
        ),
    ]
