# Generated by Django 3.1.1 on 2021-01-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_auto_20210118_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterinword',
            name='order',
            field=models.FloatField(default=99, help_text='This determines the order of the elements'),
        ),
        migrations.AlterField(
            model_name='definitionincharacter',
            name='order',
            field=models.FloatField(default=99, help_text='This determines the order of the elements'),
        ),
        migrations.AlterField(
            model_name='definitioninword',
            name='order',
            field=models.FloatField(default=99, help_text='This determines the order of the elements'),
        ),
        migrations.AlterField(
            model_name='radicalincharacter',
            name='order',
            field=models.FloatField(default=99, help_text='This determines the order of the elements'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='order',
            field=models.FloatField(default=99, help_text='This determines the order of the elements'),
        ),
        migrations.AlterField(
            model_name='wordinset',
            name='order',
            field=models.FloatField(default=99, help_text='This determines the order of the elements'),
        ),
    ]
