# Generated by Django 3.1.1 on 2021-01-23 11:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_auto_20210120_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='cndquestion',
            name='correct_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=list, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cndquestion',
            name='title_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.linkedfield'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cndquestion',
            name='wrong_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=list, size=None),
            preserve_default=False,
        ),
    ]
