# Generated by Django 3.1.1 on 2021-01-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_auto_20210123_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='chinese_highlight',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='pinyin_highlight',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='translation_highlight',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
