# Generated by Django 3.1.1 on 2021-01-23 15:40
import re
from django.db import migrations
from content.utils import punctuate_Chinese, punctuate_English


def add_highlight(s, target):
    # if already manually highlighted, do nothing
    if re.search(r"<.*?>", s):
        return re.sub(r"<(.*?)>", r"\1", s), s
    return s, re.sub(f"({target})", r'<\1>', s, flags=re.IGNORECASE)


def update(apps, schema_editor):
    Sentence = apps.get_model('content', 'Sentence')
    for sentence in Sentence.objects.all():
        sentence.chinese = punctuate_Chinese(sentence.chinese)
        sentence.chienese, sentence.chinese_highlight = \
            add_highlight(sentence.chinese, sentence.word.chinese)
        sentence.pinyin = punctuate_English(sentence.pinyin)
        sentence.pinyin, sentence.pinyin_highlight = \
            add_highlight(sentence.pinyin, sentence.word.pinyin)
        sentence.translation = punctuate_English(sentence.translation)
        definition = sentence.word.definitions.first()
        if definition:
            sentence.translation, sentence.translation_highlight = \
                add_highlight(sentence.translation, definition.definition)
        sentence.save()


def backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_auto_20210123_1517'),
    ]

    operations = [
        migrations.RunPython(update, backward)
    ]
