# Generated by Django 3.1.1 on 2021-01-26 12:03

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_audiofile'),
    ]

    operations = [
        UnaccentExtension()
    ]
