# Generated by Django 3.1.1 on 2021-01-26 12:13

import content.models.audio_file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_add_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='type',
            field=models.CharField(choices=[('taiwan', 'taiwan'), ('self', 'self recorded')], default='pinyin', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='audio',
            field=models.ForeignKey(default=content.models.audio_file.AudioFile.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='characters', related_query_name='character', to='content.audiofile'),
        ),
        migrations.AddField(
            model_name='radical',
            name='audio',
            field=models.ForeignKey(blank=True, default=content.models.audio_file.AudioFile.get_default_pk, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='radicals', related_query_name='radical', to='content.audiofile'),
        ),
        migrations.AddField(
            model_name='word',
            name='audio',
            field=models.ForeignKey(default=content.models.audio_file.AudioFile.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='words', related_query_name='word', to='content.audiofile'),
        ),
    ]
