# Generated by Django 3.1.1 on 2021-01-26 12:52
# pair audio with content

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist


def update(apps, schema_editor):
    AudioFile = apps.get_model('content', 'AudioFile')
    Radical = apps.get_model('content', 'Radical')
    Character = apps.get_model('content', 'Character')
    Word = apps.get_model('content', 'Word')

    def get_AudioFile_by_pinyin(pinyin):
        try:
            file =  AudioFile.objects.filter(content=pinyin, type='pinyin').get()
            return file
        except ObjectDoesNotExist:
            return AudioFile.objects.get_or_create(file='default.mp3',
                                         content='default',
                                         origin='default')[0]

    for word in Word.objects.filter(chinese__regex=r'^[\u2E80-\u2FD5\u3190-\u319f'
           r'\u3400-\u4DBF\u4E00-\u9FCC\uF900-\uFAAD\U00020000-\U0002A6D6]{1}$').all():
        word.audio = get_AudioFile_by_pinyin(word.pinyin)
        word.save()
    for character in Character.objects.all():
        character.audio = get_AudioFile_by_pinyin(character.pinyin)
        character.save()
    for radical in Radical.objects.all():
        if radical.pinyin:
            radical.audio = get_AudioFile_by_pinyin(radical.pinyin)
            radical.save()



def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_auto_20210126_1213'),
    ]

    operations = [
        migrations.RunPython(update, backward)
    ]
