# Generated by Django 3.1.1 on 2021-01-27 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_data_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='audiofile',
            name='archive',
            field=models.TextField(blank=True, help_text='This is auto-generated as reference. Read-only', max_length=500),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='content',
            field=models.TextField(help_text="\n        This field is used for auto searching, and (type, content) must be unique. \n        When type is pinyin, content must be pinyin with tone without any \n        whitespace to either side. When type is word, content must be chinese \n        characters. If you don't want this audio to be matched to a content object \n        automatically, set type to custom. \n        ", max_length=300),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='origin',
            field=models.CharField(choices=[('taiwan', 'taiwan'), ('baidu', 'baidu'), ('self', 'self recorded')], default='self', max_length=10),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='type',
            field=models.CharField(choices=[('taiwan', 'taiwan'), ('baidu', 'baidu'), ('self', 'self recorded')], max_length=10),
        ),
        migrations.AlterField(
            model_name='radical',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radicals', related_query_name='radical', to='content.audiofile'),
        ),
        migrations.AlterUniqueTogether(
            name='audiofile',
            unique_together={('type', 'content')},
        ),
    ]
