# Generated by Django 3.1.1 on 2021-01-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_auto_20210127_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='type',
            field=models.CharField(choices=[('pinyin', 'pinyin'), ('custom', 'custom'), ('word', 'word')], max_length=10),
        ),
    ]
