# Generated by Django 3.1.1 on 2021-01-27 12:16

import content.models.audio_file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_auto_20210127_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='audio',
            field=models.ForeignKey(default=content.models.audio_file.AudioFile.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sentences', related_query_name='sentence', to='content.audiofile'),
        ),
    ]
