# Generated by Django 3.1.1 on 2021-01-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_sentence_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='IC_level',
            field=models.IntegerField(blank=True, help_text='the first appearance of this in IC,leave blank if N/A.', null=True),
        ),
        migrations.AddField(
            model_name='radical',
            name='IC_level',
            field=models.IntegerField(blank=True, help_text='the first appearance of this in IC,leave blank if N/A.', null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='IC_level',
            field=models.IntegerField(blank=True, help_text='the first appearance of this in IC,leave blank if N/A.', null=True),
        ),
        migrations.AddField(
            model_name='wordset',
            name='IC_level',
            field=models.IntegerField(blank=True, help_text='the first appearance of this in IC,leave blank if N/A.', null=True),
        ),
    ]
