# Generated by Django 3.1.1 on 2021-01-24 15:40

import re
from django.db import migrations


def update(apps, schema_editor):
    WordSet = apps.get_model('content', 'WordSet')
    Word = apps.get_model('content', 'Word')
    Character = apps.get_model('content', 'Character')
    Radical = apps.get_model('content', 'Radical')

    for wordset in WordSet.objects.all():
        match = re.match(r'IC Lv\.(\d) Pt\.\d Lesson (\d\d?)', wordset.name)
        if not match:
            continue
        level = int(match.group(1)) * 20 + int(match.group(2)) - 20
        wordset.IC_level = level
        wordset.save()
        wordset.words.filter(IC_level__isnull=True).update(IC_level=level)
        Character.objects.filter(word__in=wordset.words.all(),
                                 IC_level__isnull=True).update(IC_level=level)
        Radical.objects.filter(character__word__in=wordset.words.all(),
                               IC_level__isnull=True).update(IC_level=level)


def reverse_update(apps, schema_editor):
    WordSet = apps.get_model('content', 'WordSet')
    Word = apps.get_model('content', 'Word')
    Character = apps.get_model('content', 'Character')
    Radical = apps.get_model('content', 'Radical')
    WordSet.objects.update(IC_level=None)
    Word.objects.update(IC_level=None)
    Character.objects.update(IC_level=None)
    Radical.objects.update(IC_level=None)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_auto'),
    ]

    operations = [
        migrations.RunPython(update, reverse_update)
    ]
