# Generated by Django 3.1.1 on 2021-01-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_IC_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='IC_level',
            field=models.IntegerField(blank=True, help_text="the first appearance of this in IC, 1 means lv1 part1 lesson 1, leave blank if it doesn't appear in IC.", null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', related_query_name='character', to='content.audiofile'),
        ),
        migrations.AlterField(
            model_name='radical',
            name='IC_level',
            field=models.IntegerField(blank=True, help_text="the first appearance of this in IC, 1 means lv1 part1 lesson 1, leave blank if it doesn't appear in IC.", null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentences', related_query_name='sentence', to='content.audiofile'),
        ),
        migrations.AlterField(
            model_name='word',
            name='IC_level',
            field=models.IntegerField(blank=True, help_text="the first appearance of this in IC, 1 means lv1 part1 lesson 1, leave blank if it doesn't appear in IC.", null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', related_query_name='word', to='content.audiofile'),
        ),
        migrations.AlterField(
            model_name='wordset',
            name='IC_level',
            field=models.IntegerField(blank=True, help_text="the first appearance of this in IC, 1 means lv1 part1 lesson 1, leave blank if it doesn't appear in IC.", null=True),
        ),
    ]
