# Generated by Django 3.1.1 on 2021-02-02 13:31

from django.db import migrations, models
from random import randint

def forward(apps, schema_editor):
    GeneralQuestion = apps.get_model('content', 'GeneralQuestion')
    GeneralQuestion.objects.all().delete()

def backward(apps, schema_editor):
   pass

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0054_cndquestion_choice_num'),
    ]

    operations = [
        migrations.RunPython(
            forward,
            backward,
        ),
        migrations.AlterModelOptions(
            name='generalquestion',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='generalquestion',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='generalquestion',
            unique_together={('reviewable', 'order')},
        ),
    ]
