# Generated by Django 3.1.1 on 2021-02-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0055_auto_20210202_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='radical',
            name='is_learnable',
            field=models.BooleanField(default=False),
        ),
    ]
