# Generated by Django 3.1.1 on 2021-02-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0056_radical_is_learnable'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='memory_aid_highlight',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
