# Generated by Django 3.1.1 on 2021-02-17 05:27

from django.db import migrations, models
import django.db.models.deletion

import mptt.fields
import mptt
import mptt.managers


def forward(apps, schema_editor):
    manager = mptt.managers.TreeManager()
    WordSet = apps.get_model('content', 'WordSet')
    manager.model = WordSet
    mptt.register(WordSet, order_insertion_by=['name'])
    manager.contribute_to_class(WordSet, 'objects')
    manager.rebuild()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0056_radical_is_learnable'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordset',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordset',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='child', to='content.wordset'),
        ),
        migrations.AddField(
            model_name='wordset',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordset',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.RunPython(
            forward, backward, elidable=True
        )
    ]
