# Generated by Django 3.1.1 on 2021-02-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0057_auto_20210217_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='jiezi_id',
            field=models.CharField(default='x', max_length=20),
            preserve_default=False,
        ),
    ]
