# Generated by Django 3.1.1 on 2021-03-11 06:40

import logging
from django.db import migrations


def forward(apps, schema_editor):
    CNDQuestion = apps.get_model('content', 'CNDQuestion')
    Word = apps.get_model('content', 'Word')
    words = Word.objects.filter(chinese__contains='(')
    logging.info(CNDQuestion.objects.filter(reviewable__word__in=words).delete())


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0061_more_sentence_highlight'),
    ]

    operations = [
        migrations.RunPython(forward, backward, elidable=True)
    ]
