# Generated by Django 3.1.1 on 2021-03-14 16:37

from django.db import migrations
import logging


def forward(apps, schema_editor):
    models = ('Word', 'Character', 'Radical')
    replacements = (
        ('indicate', 'show'),
        ('suggest', 'show'),
        ('depicts', 'looks like'),
        ('refers to', 'means'),
        ('pronunciation', 'pinyin'),
    )
    for model_name in models:
        Model = apps.get_model('content', model_name)
        for original, replacement in replacements:
            memaid_name = 'memory_aid' if model_name != 'Radical' \
                else 'explanation'
            qs = Model.objects.filter(**{f"{memaid_name}__contains": original})
            for obj in qs:
                old_memaid = getattr(obj, memaid_name)
                new_memaid = old_memaid.replace(original, replacement)
                setattr(obj, memaid_name, new_memaid)
                obj.save()
                logging.info('%r \r\n "%s" \r\n => \r\n "%s"',
                             obj, old_memaid, new_memaid)


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0062_CND_brackets_fix'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
