# Generated by Django 3.1.1 on 2021-03-25 13:30

from django.db import migrations, models
import unicodedata
import re
import logging


def unaccent(s):
    return unicodedata.normalize('NFKD', s).encode('ascii','ignore'
                                                   ).decode('utf-8')

def forward(apps, schema_editor):
    models = ('Word', 'Character', 'Radical')
    for model_name in models:
        Model = apps.get_model('content', model_name)
        for obj in Model.objects.all():
            if not obj.pinyin or 'TODO' in obj.pinyin:
                continue
            obj.searchable_pinyin = re.sub(r'[\ \(\)\-\,\'\.\/]', r'', unaccent(obj.pinyin).lower())
            obj.save()
            if re.match(r'^\w+$', obj.searchable_pinyin) is None:
                logging.warning("%r '%s' => '%s'", obj, obj.pinyin, obj.searchable_pinyin)


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0064_dumbify_memaid_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='searchable_pinyin',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='radical',
            name='searchable_pinyin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='searchable_pinyin',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.RunPython(forward, backward),
    ]
