# Generated by Django 3.1.1 on 2021-03-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0065_auto_20210325_1330'),
        ('content', '0065_MC_context_add_parenthesis'),
    ]

    operations = [
    ]
