# Generated by Django 3.1.1 on 2021-04-08 08:52

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0067_auto_20210326_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbquestion',
            name='alternative_answers',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, default=list, help_text='all punctuations and spaces will be ignored', size=None),
        ),
        migrations.AlterField(
            model_name='cndquestion',
            name='correct_answers',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=5), size=None),
        ),
        migrations.AlterField(
            model_name='cndquestion',
            name='wrong_answers',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=5), size=None),
        ),
    ]
