# Generated by Django 3.1.1 on 2021-04-19 11:39

from django.db import migrations
from django.core import management


def forward(apps, schema_editor):
    management.call_command('createinitialrevisions')


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0070_auto_20210408_0943'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
